export { HeaderContainer as Header } from './Header/HeaderContainer';
export { SearchContainer as Search } from './Search/SearchContainer';
export { Content } from './Content';
export { ListDishesContainer as ListDishes } from './ListDishes/ListDishesContainer';
export { SelectTypeOrderContainer as SelectTypeOrder } from './SelectTypeOrder/SelectTypeOrderContainer';
export { DishCard } from './DishCard/';
export { AsideNewOrder } from './AsideNewOrder';
export { RadioTypeOrderContainer as RadioTypeOrder } from './RadioTypeOrder/RadioTypeOrderContainer';
export { FormOrder } from './FormOrder';
export { OrderCardContainer as OrderCard } from './OrderCard/OrderCardContainer';
export { FormOrderBodyContainer as FormOrderBody } from './FormOrderBody/FormOrderBodyContainer';
